# Generated by Django 4.2.1 on 2023-06-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
                ('temperature', models.DateTimeField()),
            ],
            options={
                'db_table': 'donnees',
                'managed': False,
            },
        ),
    ]
